const Bloglist = [
    {
        id: 1,
        category: "Cyber security", 
        Heading: "How you stay safe from attackers ?", 
        image: "/shivapuri.jpg",
        alter:"first blog", 
        author_image: "/gump.jpg", 
        author: "Kapil pant", 
        date:  "march 2", 
        meta: "short description about this blog in 2 lines", 
        description: " Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.",
        slug:"a-day-hike-to-shivapuri-National-park"
    },
    {
        id: 2,
        category: "Cyber security", 
        Heading: "How do they hack us in real?", 
      image: "/shivapuri.jpg",
        alter:"drawing blog", 
        author_image: "/gump.jpg", 
        author: "Samir Pradhan", 
        date: "june 2", 
        meta: "short description about this blog in 2 lines", 
        description: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.. Thank you very much ",
        slug:"how-to-draw-simple-things"
    },
    {
        id: 3,
        category: "Coding", 
        Heading: "Best way to start coding ?", 
        image: "/shivapuri.jpg",
        alter:"drawing asddblog", 
        author_image: "/gump.jpg", 
        author: "Samir Pradhan", 
        date: "june 2", 
        meta: "short description about this blog in 2 lines", 
        description: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups. Thank you very much ",
        slug:"how-to-write-code-in"
    },
    {
        id: 4,
        category: "Drawings", 
        Heading: "Story behind my drawings ?", 
        image: "/shivapuri.jpg",
        alter:"drawing asasdddblog", 
        author_image: "/gump.jpg", 
        author: "Samir Pasdaaradhan", 
        date: "junasdasde 2", 
        meta: "short description about this blog in 2 lines", 
        description: "Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups. Thank you very much ",
        slug:"how-to-asd-code-in"
    },
    {
        id: 5,
        category: "Travel", 
        Heading: "Trip to Shivapuri National park", 
        image: "/shivapuri.jpg",
        alter:"drawdddblog", 
        author_image: "/gump.jpg", 
        author: "Saaaradhan", 
        date: "ju 2",
        meta: "short description about this blog in 2 lines", 
        description: "ThiLorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups. Thank you very much ",
        slug:"how-tode-in"
    },
    {
        id: 6,
        category: "Coding", 
        Heading: "What are basics in HTML|CSS ?", 
        image: "/shivapuri.jpg",
        alter:"drblog", 
        author_image: "/gump.jpg", 
        author: "Sradhan", 
        date: "july 2", 
        meta: "short description about this blog in 2 lines", 
        description: "Thi blog 2Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups. Her name is sita. Thank you very much ",
        slug:"how-tod-asd-asde-in"
    },
    {
        id: 7,
        category: "Coding", 
        Heading: "What are basics in HTML|CSS ?", 
        image: "/shivapuri.jpg",
        alter:"drblog", 
        author_image: "/gump.jpg", 
        author: "Sradhan", 
        date: "july 2", 
        meta: "short description about this blog in 2 lines", 
        description: "Thi blog 2 Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups. Thank you very much ",
        slug:"how-tas-qw-wq-od-asd-asde-in"
    },
    {
        id: 8,
        category: "Coding", 
        Heading: "What are basics in HTML|CSS ?", 
        image: "/shivapuri.jpg",
        alter:"drblog", 
        author_image: "/gump.jpg", 
        author: "Sradhan", 
        date: "july 2", 
        meta: "short description about this blog in 2 lines", 
        description: "Thi blog 2 , written by Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups. is sita. Thank you very much ",
        slug:"how-t-sa-saod-asd-asde-in"
    },
    {
        id: 9,
        category: "Coding", 
        Heading: "What are basics in HTML|CSS ?", 
        image: "/shivapuri.jpg",
        alter:"drblog", 
        author_image: "/gump.jpg", 
        author: "Sradhan", 
        date: "july 2", 
        meta: "short description about this blog in 2 lines", 
        description: "Thi blog 2 , written by samLorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups. Thank you very much ",
        slug:"how-tod-asas-d-asde-in"
    }
   
]
export default Bloglist;  