import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Navbartwo from '../components/Navbar/Navbartwo';
import styles from '../styles/Gallery.module.css';
import Gallerylist from "../components/gallerylist";
import Footer from "../components/Footer";
const Gallery = () => {
  const [items] = useState(Gallerylist);
  return (
    <>

      <Head>
        <title>Kapil Dev Pant</title>
        <meta name="kapil dev pant" content="This website is replica of older site i.e kapilpant157.com.np, generated by create next app" />
        <link rel="icon" href="/sign.ico" />
      </Head>
      <div className={styles.header}>
        <h1>Take nothing but Photoes Leave nothing but footprints</h1>
      </div>
      <div className={styles.wrapper}>
      {items.map((elem) => {
             const { name, image, alta} = elem;
             return (
        <div className={styles.parent} key={elem.id} >
          <div className={styles.child}>
                <Image src={image}  height={533} width={800} alt={alta} />
            <div className={styles.span}>{name}</div>
          </div>
        </div>
             );
      })}
      </div> 

      <Navbartwo/>
      <div className="footer"> 
        <Footer/>
      </div>

    </>
  )
}

export default Gallery