import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from './components/Navbar/Navbar'
import Navbartwo from './components/Navbar/Navbartwo'

export default function Home() {
  return (
    <>
    <div className={styles.container}>
    <Head>
        <title>Kapil Dev Pant</title>
        <meta name="laksdj a" content="Generated by create next app" />
        <link rel="icon" href="/sign.ico" />
      </Head>
      <Navbar/>
      <Navbartwo/>
      </div>
    </>
  )
}
