import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Navbartwo from "../components/Navbar/Navbartwo";
import Footer from "../components/Footer";

const images = [
  {
    id: 1,
    imageName: "/ca.jpg",
    tag: "Completed Projects",
    title: "R Pandey and Associates",
    type: "Charted Accountant",
    caption:
      "R. Pandey & Associates is a leading Accounting and Consulting Firm of Nepal offering a wide range of services in the field of Audit, Risk Advisory, Tax Advisory, M&A Advisory and Managed Services for National and Multinational Companies of all sizes.",
    link: "https://rpanepal.com.np/",
  },
  {
    id: 2,
    imageName: "/gyanhub.jpg",
    tag: "Ongoing Projects",
    title: "Gyann Hub",
    type: "Educational",
    caption:
      "Gyannhub is educational portal, established for distribution of notes prepared by students and teachers of various levels",
    link: "https://gyannhub.com/",
  },
  {
    id: 3,
    imageName: "/mayapp.jpg",
    tag: "Completed Projects",
    title: "Maya Party Palace",
    type: "Party Venue",
    caption:
      "Maya party palace is best known for its outstanding peaceful environment, excellent staff service and best management. With the very best food items and taste that makes everyone think to get more celebrations here.",
    link: "https://dreamy-noyce-adaddb.netlify.app",
  },
  {
    id: 4,
    imageName: "/tgn.jpg",
    tag: "Completed Projects",
    title: "Travel Green Nepal",
    type: "Travelling",
    caption:
      "Taking various travelling spots in nepal, TGN is established in order to probide informaton about tourism potential places in Nepal. we soon are planning on organizing events for booking and exploring various parts of NEPAL",
    link: "https://travelgreennepal.com",
  },
  {
    id: 5,
    imageName: "/kapildevpant-com-np.jpg",
    tag: "Completed Projects",
    title: "Map of Nepal",
    type: "Districts",
    caption: "Personal Domain listing all districts of nepal",
    link: "https://kapildevpant.com.np",
  },
  {
    id: 6,
    imageName: "/construction.jpg",
    tag: "Completed Projects",
    title: "Construction Company",
    type: "Construction",
    caption:
      "ON Sale!!! ON Sale!!! ON Sale!!! , project is suitable for Construction company, Build on Reactjs makes it super fast and fully responsice. If interested in buying in affordable price, you know what to do, just send a message. ",
    link: "https://youtu.be/f3Qv4qa1w0A",
  },
  {
    id: 7,
    imageName: "/construction.jpg",
    tag: "Completed Projects",
    title: "Pant Family Tree",
    type: "Construction",
    caption:
      "this is upcomming project that is based on genealogy  ",
    link: "#",
  }
];

function Projects() {
  const [tag, setTag] = useState("all");
  const [filteredImages, setFilteredImages] = useState([]);

  useEffect(() => {
    tag === "all"
      ? setFilteredImages(images)
      : setFilteredImages(images.filter((image) => image.tag === tag));
  }, [tag]);

  return (
    <section>
    <div className="services_">
      <Head>
        <title>Kapil Dev Pant</title>
        <meta name="laksdj a" content="Generated by create next app" />
        <link rel="icon" href="/sign.ico" />
      </Head><Navbartwo />
      <div className="title">
            <h3>One step at a time is way to summit</h3>
        </div>
      <div className="tags">
        <TagButton
          name="all"
          tagActive={tag === "all" ? true : false}
          handleSetTag={setTag}
        />
        <TagButton
          name="Ongoing Projects"
          tagActive={tag === "Ongoing Projects" ? true : false}
          handleSetTag={setTag}
        />
        <TagButton
          name="Completed Projects"
          tagActive={tag === "Completed Projects" ? true : false}
          handleSetTag={setTag}
        />
      </div>

      <div className="container">
        {filteredImages.map((image) => (
          <div className="dupli-row" key={image.id}>
            <div className="portfolio-item">
              <a className="portfolio-link" href={image.link} >
                <Image className="imge-fluid" src={image.imageName} alt="asd" height={275} width={300} ></Image>
              </a>
              <div className="portfolio-caption">
                <h2>{image.title}</h2>
                <p>{image.type}</p>
              </div>
            </div>
          </div>
        ))}
      </div>
      <div className="footer"> 
        <Footer/>
      </div>
    </div>
</section>
  );
}
const TagButton = ({ name, handleSetTag, tagActive }) => {
  return (
    <button
      className={`tag ${tagActive ? "activetags" : null}`}
      onClick={() => handleSetTag(name)}
    >
      {name.toUpperCase()}
    </button>
  );
};

export default Projects;
